@CarrierRatesQuery.MockFedEx_HostAddress = http://localhost:5133

POST {{CarrierRatesQuery.MockFedEx_HostAddress}}/api/fedex/rates
Accept: application/json
Content-Type: application/json

{
  "package": {
    "weight": 5,
    "dimensions": {
      "length": 10,
      "width": 5,
      "height": 5
    }
  }
}

###
