@CarrierRatesQuery.MockUps_HostAddress = http://localhost:5104

POST {{CarrierRatesQuery.MockUps_HostAddress}}/api/ups/shipping-rates
Accept: application/json
Content-Type: application/json

{
  "shipment": {
    "weightLbs": 11,
    "dimensionsInches": {
      "length": 10,
      "width": 5,
      "height": 5
    }
  }
}

###
