@CarrierRatesQuery.MockDhl_HostAddress = http://localhost:5204

POST {{CarrierRatesQuery.MockDhl_HostAddress}}/api/dhl/rates
Accept: application/json
Content-Type: application/json

{
  "parcel": {
    "weightKg": 5,
    "sizeCm": {
      "length": 10,
      "width": 5,
      "height": 5
    }
  }
}

###
